apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-conf
  namespace: opentelemetry-operator-system
  labels:
    app: aws-adot
    component: adot-collector-conf
data:
  adot-collector-config: |
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 15s
            scrape_timeout: 10s

          scrape_configs:
            - job_name: 'kubernetes-pod-jmx'
              sample_limit: 10000
              metrics_path: /metrics
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [ __address__ ]
                  action: keep
                  regex: '.*:9404$'
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - action: replace
                  source_labels: [ __meta_kubernetes_namespace ]
                  target_label: Namespace
                - source_labels: [ __meta_kubernetes_pod_name ]
                  action: replace
                  target_label: pod_name
                - action: replace
                  source_labels: [ __meta_kubernetes_pod_container_name ]
                  target_label: container_name
                - action: replace
                  source_labels: [ __meta_kubernetes_pod_controller_kind ]
                  target_label: pod_controller_kind
                - action: replace
                  source_labels: [ __meta_kubernetes_pod_phase ]
                  target_label: pod_controller_phase
              metric_relabel_configs:
                - source_labels: [ __name__ ]
                  regex: 'jvm_gc_collection_seconds.*'
                  action: keep
    exporters:
      awsprometheusremotewrite:
        endpoint: {{ .Values.ampurl }}
        aws_auth:
          region: {{ .Values.region }}
          service: "aps"
      logging:
        loglevel: info
    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679
    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [logging, awsprometheusremotewrite]