apiVersion: v1
kind: Service
metadata:
  name: adot-collector
  namespace: opentelemetry-operator-system
  labels:
    app: aws-adot
    component: adot-collector
spec:
  ports:
  - name: metrics
    port: {{ .Values.prometheusMetricsPort }}
  selector:
    component: adot-collector
  type: NodePort